# configs/trainer/video.yaml

# 进行训练的周期数，即模型在全部训练集上迭代的次数
max_epochs: 40

# 训练使用的加速器类型，此处指定为GPU加速
accelerator: "gpu"

# 指定使用的GPU设备编号，此处仅使用第一个GPU
devices: [ 0 ]

# 精度模式，"16-mixed" 表示使用混合精度训练，有助于加速训练和减少内存使用
precision: "16-mixed"

# 指定训练策略，此处使用 'ddp_find_unused_parameters_true' 策略
strategy: 'ddp_find_unused_parameters_true'

# 限制训练集批次的比例，1.0 表示使用全部批次
limit_train_batches: 1.0
# 限制验证集批次的比例，1.0 表示使用全部批次
limit_val_batches: 1.0
# 限制测试集批次的比例，1.0 表示使用全部批次
limit_test_batches: 1.0

profiler: "simple"