# configs/evaluator/phoenix2014.yaml

gt_file:
  train: ../data/global_files/ground_truth/phoenix2014-groundtruth-train_sorted.stm
  dev: ../data/global_files/ground_truth/phoenix2014-groundtruth-dev_sorted.stm
  test: ../data/global_files/ground_truth/phoenix2014-groundtruth-test_sorted.stm

sclite_bin: '../.bin/sclite'
cleanup: false
