# configs/models/model1.yaml

# 模型配置文件，用于定义模型的各种参数和设置

# 定义模型要预测的类别数量
num_classes: 1296

# 指定使用的卷积类型
conv_type: 2

# 是否使用批量归一化（Batch Normalization）
use_bn: false

# 定义模型的隐藏层大小
hidden_size: 1024

# 学习率（Learning Rate）
lr: 0.0001

# 权重衰减（Weight Decay），用于正则化，防止过拟合
weight_decay: 0.0001

# 学习率调度器的里程碑设置，为空表示不使用学习率调度
lr_scheduler_milestones: null

# 学习率调度器的乘法因子，用于在里程碑时调整学习率
lr_scheduler_gamma: 0.2

# 上次训练的最后一个epoch，用于继续训练
last_epoch: -1

# 是否在测试阶段使用特定参数设置
test_param: false

# 是否启用权重归一化，有助于提高模型的泛化能力
weight_norm: true

