# configs/model/CorrNet.yaml

name: "CorrNet"

# for after backward
test_param: false

# for network
conv_type: 2
use_bn: false
hidden_size: 1024
share_classifier: true
resnet_pretrained: true
pretrained_model_dir: ../.cache/pretrained_models/

# for optimizer and lr_scheduler
lr: 0.0001
weight_decay: 0.0001
# lr scheduler
milestones: [ 20, 35 ]
gamma: 0.2
last_epoch: -1

# for loss
loss_weights: [ 1.0, 1.0, 25.0 ]

# for callbacks checkpoint
save_last: true
save_top_k: 3
