# configs/model/model1.yaml

# for common
test_param: false

# for network
num_classes: 1296
conv_type: 2
use_bn: false
hidden_size: 1024

# for optimizer and lr_scheduler
lr: 0.0001
weight_norm: true
weight_decay: 0.0001
lr_scheduler_milestones: null
lr_scheduler_gamma: 0.2
last_epoch: -1

# for evaluation
evaluation_sh_path: './evaluation'  # 评估脚本路径
evaluation_sclite_path: '../.bin/sclite'  # sclite评估工具路径
remove_eval_tmp_file: false
