# configs/model/MSKA.yaml

# for after backward
test_param: false


# for optimizer and lr_scheduler
lr: 0.0001
weight_decay: 0.0001
# lr scheduler
milestones: [ 20, 35 ]
gamma: 0.2
last_epoch: -1

# for loss
loss_weights: [ 1.0, 1.0, 25.0 ]

# for early stop
patience_early_stop: 50

# for callbacks checkpoint
save_last: true
save_top_k: 3