# configs/dataset/csl-daily.yaml

data_cfgs:
  dataset_dir: "../data/csl-daily"
  #features_dir: "../data/csl-daily/sentence_frames-512x512/frames_512x512"
  features_dir: "../data/preprocess/csl-daily/frames_256x256"
  #annotations_dir: "../data/csl-daily/sentence_label"
  #split_file: "../data/csl-daily/sentence_label/split_1.txt"

# keypoints
keypoints_file: "../data/keypoints/kps_info/csl-daily-keypoints.pkl"

# groundtruth
gloss_groundtruth_file:
  train: ../data/global_files/ground_truth/csl-daily-groundtruth-train.stm
  dev: ../data/global_files/ground_truth/csl-daily-groundtruth-dev.stm
  test: ../data/global_files/ground_truth/csl-daily-groundtruth-test.stm

# vocab
gloss_vocab_file: ../slr/datasets/vocabs/csl-daily_gloss_vocab.txt
