# configs/dataset/csl-daily.yaml

dataset_dir: "../data/csl-daily"

# special dirs
#features_dir: "../data/csl-daily/sentence_frames-512x512/frames_512x512"
#annotations_dir: "../data/csl-daily/sentence_label"
#split_file: "../data/csl-daily/sentence_label/split_1.txt"

# dataloader params
batch_size: 2
num_workers: 8

read_tensor: true
