# configs/dataset/phoenix2014.yaml

data_cfgs:
  dataset_dir: "../data/phoenix2014"
  features_dir: "../data/phoenix2014/phoenix-2014-multisigner/features/fullFrame-256x256px"
  #features_dir: "/media/xzj23/disk-zj-ext4/transformed_data/phoenix2014_features"
  #annotations_dir: "../data/phoenix2014/phoenix-2014-multisigner/annotations/manual"

# keypoints
keypoints_file: "../data/keypoints/kps_info/phoenix2014-keypoints.pkl"

# groundtruth
gloss_groundtruth_file:
  train: ../data/global_files/ground_truth/phoenix2014-groundtruth-train_sorted.stm
  dev: ../data/global_files/ground_truth/phoenix2014-groundtruth-dev_sorted.stm
  test: ../data/global_files/ground_truth/phoenix2014-groundtruth-test_sorted.stm

# vocab
gloss_vocab_file: ../slr/datasets/vocabs/phoenix2014_gloss_vocab.txt
