# configs/dataset/phoenix2014T.yaml

dataset_dir: "../data/phoenix2014T"

# special dirs
features_dir: "../data/preprocess/phoenix2014T/frames_256x256"
#features_dir: "../data/phoenix2014T/PHOENIX-2014-T/features/fullFrame-256x256px"
#annotations_dir: "../data/phoenix2014T/PHOENIX-2014-T/annotations/manual"

# dataloader params
batch_size: 2
num_workers: 8

read_hdf5: false
