# configs/dataset/phoenix2014.yaml

dataset_dir: "../data/phoenix2014"

# special dirs
features_dir: "../data/phoenix2014/phoenix-2014-multisigner/features/fullFrame-256x256px"
#annotations_dir: "../data/phoenix2014/phoenix-2014-multisigner/annotations/manual"

# dataloader params
batch_size: 2
num_workers: 8
