# configs/dataset/phoenix2014.yaml

dataset_dir: "../data/phoenix2014"

# special dirs
features_dir: "../data/phoenix2014/phoenix-2014-multisigner/features/fullFrame-256x256px"
#features_dir: "/media/xzj23/disk-zj-ext4/transformed_data/phoenix2014_features"
#annotations_dir: "../data/phoenix2014/phoenix-2014-multisigner/annotations/manual"

# dataloader params
batch_size: 2
num_workers: 8

read_hdf5: false
