# configs/dataset/Phoenix2014.yaml

name: "Phoenix2014"

data_cfgs:
  dataset_dir: "../data/phoenix2014"
  features_dir: "../data/preprocessed/phoenix2014/frames-256x256px" # if null, use default features directory in $dataset_dir
  annotations_dir: null # if null, use default annotations directory in $dataset_dir

# keypoints
keypoints_file: "../data/preprocessed/phoenix2014/phoenix2014-keypoints-mska.pkl"

# for recognition
glosses_groundtruth_file:
  train: "../data/preprocessed/phoenix2014/phoenix2014-glosses-groundtruth-train.stm"
  dev: "../data/preprocessed/phoenix2014/phoenix2014-glosses-groundtruth-dev.stm"
  test: "../data/preprocessed/phoenix2014/phoenix2014-glosses-groundtruth-test.stm"

gloss_vocab_file: "../data/preprocessed/phoenix2014/phoenix2014-gloss-vocab.txt"
