# /configs/common_base.yaml

defaults:
  - _self_
  - dataset: null
  - model: null
  - dataloader: null
  - trainer: null
  - decoder: tf_ctc_beam_search
  - recognition_evaluator: python
  - translation_evaluator: python
  - tokenizer: simple_tokenizer
  - logger: wandb

# 项目相关配置
project: null
name: null
times: 0

model_name: null
dataset_name: null
dataset_type: null

decoder_name: TFCTCBeamSearchDecoder
recognition_evaluator_name: python
translation_evaluator_name: python
tokenizer_name: SimpleTokenizer

checkpoint: null # if null, no checkpoint loading

# 其他配置
seed: -1
save_dir: ../experiments

torch_num_threads: 12
torch_float32_matmul_precision: high

convert_to_onnx: true

