# /configs/config.yaml

defaults:
  - _self_
  - dataset: null
  - model: null
  - dataloader: null
  - trainer: null
  - recognition: default
  - translation: default
  - logger: wandb


# 项目相关配置
project: null
name: null
times: 0

data_type: null

checkpoint: null # if null, no checkpoint loading

# 其他配置
seed: -1
save_dir: ../experiments

num_threads: 12

torch_float32_matmul_precision: high

convert_to_onnx: true


# Hydra 运行配置
hydra:
  run:
    dir: ../experiments/${project}/${name}/${times}/hydra
