# /configs/CorrNet_Phoenix2014_experiment.yaml
defaults:
  - _self_ # 自引用，确保此配置文件被包含
  - dataset: phoenix2014 # 数据集配置
  - tokenizer: phoenix2014
  - model: CorrNet # 模型配置
  - decoder: ctc_beam_search
  - evaluator: phoenix2014
  - trainer: use_gpu # 训练配置
  - callback: default # 回调函数配置
  - logger: wandb # 日志记录器配置


# Hydra 运行配置
hydra:
  run:
    # 实验目录结构
    dir: ../experiments/${project}/${name}/${timestamp}/hydra


# 项目相关配置
project: Phoenix2014_new
name: CorrNet_with_normalization_ttt
timestamp: ${now:%Y-%m-%d_%H-%M-%S}

model_name: CorrNet
dataset_name: phoenix2014

# 其他配置
seed: -1
save_dir: ../experiments

torch_num_threads: 10
torch_float32_matmul_precision: high

convert_to_onnx: true

