# experiments/example2/config.yaml
defaults:
  - hydra:../config.yaml # 引用主配置文件
  - data: phoenix2014 # 数据集配置
  - preprocess: phoenix2014 # 预处理配置
  - train: default # 训练配置
  - models: phoenix2014 # 模型配置
  - callback: default # 回调函数配置
  - logger: wandb # 日志记录器配置

experiment:
  project: example2 # 项目名称
  name: example2 # 实验名称

# 具体配置项
data:
  path: /path/to/data/phoenix2014
  split: 0.7 # 训练集占比

preprocess:
  feature_extraction: mel_spectrogram # 特征提取方法
  window_size: 0.025 # 窗口大小
  window_stride: 0.01 # 窗口步长

train:
  epochs: 150 # 训练轮次
  batch_size: 64 # 批大小
  learning_rate: 0.0005 # 学习率

models:
  architecture: vgg # 模型架构
  num_classes: 10 # 类别数量

callback:
  monitor: val_accuracy # 监控指标
  mode: max # 监控模式
  save_top_k: 5 # 保存前k个最佳模型

logger:
  project: example2 # Wandb项目名称
  entity: your_entity # Wandb实体
