# experiments/example1.yaml
defaults:
  - _self_ # 自引用，确保此配置文件被包含
  - data: phoenix2014 # 数据集配置
  - datamodule: phoenix2014_debug # 数据模块配置
  - model: model1 # 模型配置
  - trainer: use_gpu_debug # 训练配置
  - callback: default # 回调函数配置
  - logger: wandb # 日志记录器配置


# Hydra 运行配置
hydra:
  run:
    # 实验目录结构
    dir: ../experiments/${project}/${name}/${timestamp}/hydra

# 项目相关配置
project: Phoenix2014 # 项目名称
name: experiment_debug # 实验名称
timestamp: ${now:%Y-%m-%d_%H-%M-%S} # 更新时间戳格式为带下划线分隔

# 其他配置
seed: -1 # 随机数种子
save_dir: ../experiments
torch_float32_matmul_precision: high
