# /configs/exp_patchmodel_csldaily.yaml

defaults:
  - common_patch_kps
  - _self_
  - override dataset: phoenix2014 # 数据集配置
  - override model: PatchModel # 模型配置

# 项目相关配置
project: Phoenix2014_Experiment
name: PatchModel
times: 0

task: [ "recognition" ] #, "translation" ]

dataset:
  data_cfgs:
    features_dir: null
