# /configs/exp_xmodel_phoenix2014.yaml

defaults:
  - common_video
  - _self_
  - override dataset: phoenix2014T # 数据集配置
  - override model: XModel # 模型配置

# 项目相关配置
project: Phoenix2014T_Experiment
name: XModel
times: 0

task: [ "recognition" ] #, "translation" ]
