# /configs/exp_xmodel_csldaily.yaml

defaults:
  - common_video
  - _self_
  - override dataset: csl-daily # 数据集配置
  - override model: XModel # 模型配置

# 项目相关配置
project: CSL-Daily_Experiment
name: XModel
times: 0

task: [ "recognition" ] #, "translation" ]
