# /configs/exp_mska_csldaily.yaml

defaults:
  - common_keypoint
  - _self_
  - common_hydra
  - override dataset: csl-daily # 数据集配置
  - override model: MSKA # 模型配置

# 项目相关配置
project: CSL-Daily_Experiment
name: MSKA
times: 0

model_name: MSKA
dataset_name: csl-daily-keypoint
