# /configs/exp_corrnet_phoenix2014T.yaml

defaults:
  - common_video
  - _self_
  - override dataset: phoenix2014T # 数据集配置
  - override model: CorrNet # 模型配置

# 项目相关配置
project: Phoenix2014T_Experiment
name: CorrNet
times: 0

model_name: CorrNet
dataset_name: phoenix2014T
