# /configs/exp_mska_phoenix2014.yaml

defaults:
  - common_keypoint
  - _self_
  - override dataset: phoenix2014 # 数据集配置
  - override model: MSKA # 模型配置

# 项目相关配置
project: Phoenix2014_Experiment
name: MSKA
times: 0

model_name: MSKA
dataset_name: phoenix2014-keypoint

task: ["recognition", "translation"]
