# /configs/exp_stka_csldaily.yaml

defaults:
  - common_keypoint
  - _self_
  - common_hydra
  - override dataset: csl-daily # 数据集配置
  - override model: STKA # 模型配置

# 项目相关配置
project: CSL-Daily_Experiment
name: STKA
times: 0

model_name: STKA
dataset_name: csl-daily-keypoint
