# /configs/exp_corrnet_csldaily.yaml

defaults:
  - common_video
  - _self_
  - common_hydra
  - override dataset: csl-daily # 数据集配置
  - override model: CorrNet # 模型配置

# 项目相关配置
project: CSL-Daily_Experiment
name: CorrNet
times: 0

model_name: CorrNet
dataset_name: csl-daily
