# /configs/CorrNet_Phoenix2014_experiment.yaml
defaults:
  - _self_ # 自引用，确保此配置文件被包含
  - dataset: phoenix2014 # 数据集配置
  - dataloader: keypints
  - tokenizer: simple_tokenizer
  - model: CorrNet # 模型配置
  - decoder: ctc_beam_search
  - evaluator: sclite
  - trainer: use_gpu # 训练配置
  - logger: wandb # 日志记录器配置


# Hydra 运行配置
hydra:
  run:
    # 实验目录结构
    dir: ../experiments/${project}/${name}/${times}/hydra


# 项目相关配置
project: Phoenix2014_kps_debug
name: MSKA
times: 2

model_name: MSKA
dataset_name: phoenix2014-keypoint
dataset_type: "keypoint"

checkpoint: null # if null, no checkpoint loading

# 其他配置
seed: -1
save_dir: ../experiments

torch_num_threads: 12
torch_float32_matmul_precision: high

convert_to_onnx: true

