# /configs/CorrNet_Phoenix2014_experiment.yaml

defaults:
  - _self_ # 自引用，确保此配置文件被包含
  - dataset: csl-daily # 数据集配置
  - dataloader: keypoints
  - tokenizer: simple_tokenizer
  - model: MSKA # 模型配置
  - decoder: tf_ctc_beam_search
  - evaluator: python
  - trainer: keypoints # 训练配置
  - logger: wandb # 日志记录器配置

# Hydra 运行配置
hydra:
  run:
    dir: ../experiments/${project}/${name}/${times}/hydra

# 项目相关配置
project: CSL-Daily_Experiment-debug
name: MSKA
times: 302

model_name: MSKA
dataset_name: csl-daily-keypoint
dataset_type: "keypoint"
decoder_name: TFCTCBeamSearchDecoder
tokenizer_name: SimpleTokenizer
evaluator_name: python

checkpoint: null # if null, no checkpoint loading

# 其他配置
seed: -1
save_dir: ../experiments

torch_num_threads: 12
torch_float32_matmul_precision: high

convert_to_onnx: true

