# configs/config.yaml
hydra:
  run:
    dir: ../experiments/${project}/${name}/${timestamp}

# 主项目名称
project: "Phoenix2014"
#project: "Phoenix2014T"

# 实验名称配置
name: "experiment_1"

# 时间戳
timestamp: ${now:%Y-%m-%d-%H-%M-%S}

# 日志记录器配置
logger:
  offline: false
  save_dir: "../experiments"

# 回调配置
callback:
  save_dir: "../experiments"
  monitor: "val_loss"
  mode: "min"
  save_last: true
  save_top_k: 1

# 预处理配置
preprocess:
  name: "phoenix2014"
  features_path: "../data/phoenix2014/phoenix-2014-multisigner/features/fullFrame-256x256px"
  annotations_path: "../data/phoenix2014/phoenix-2014-multisigner/annotations/manual"
  gloss_dict_path: "../data/global_files/gloss_dict"
  ground_truth_path: "../data/global_files/ground_truth"
#  name: "phoenix2014T"
#  features_path: "../data/phoenix2014T/PHOENIX-2014-T/features/fullFrame-210x260px"
#  annotations_path: "../data/phoenix2014T/PHOENIX-2014-T/annotations/manual"
#  gloss_dict_path: "../data/global_files/gloss_dict"
#  ground_truth_path: "../data/global_files/ground_truth"

# 训练配置
train:
  num_workers: 8
  batch_size: 2
  n_epochs: 40
  accelerator: "gpu"
  devices: [ 1 ]
  precision: "16-mixed"
  save_path: "../experiments"
  sh_path: "./evaluation"
#  mer_path: "./evaluation"
  sclite_path: "../.bin/sclite"
  torch_float32_matmul_precision: "medium"

# 模型配置
model:
  num_classes: 1296
#  num_classes: 1116
  conv_type: 2
  use_bn: false
  hidden_size: 1024
  lr: 0.0001
  weight_decay: 0.0001
  lr_scheduler_milestones: null
  lr_scheduler_gamma: 0.2
  last_epoch: -1
  test_param: false
  weight_norm: true

# 其他配置
seed: -1
