# /configs/recognition/default.yaml

defaults:
  - tokenizer: simple_tokenizer
  - decoder: ctc_beam_search
  - evaluator: sclite
  - _self_

tokenizer_name: SimpleTokenizer
decoder_name: CTCBeamSearchDecoder
evaluator_name: sclite
