# configs/train/use_gpu.yaml

# 工作线程数，用于数据加载等操作
num_workers: 8

# 训练的批量大小，控制每次训练处理的样本数量
batch_size: 2

# 进行训练的周期数，即模型在全部训练集上迭代的次数
n_epochs: 40

# 训练使用的加速器类型，此处指定为GPU加速
accelerator: "gpu"

# 指定使用的GPU设备编号，此处仅使用第一个GPU
devices: [ 0 ]

# 精度模式，"16-mixed" 表示使用混合精度训练，有助于加速训练和减少内存使用
precision: "16-mixed"

# 模型训练结果的保存路径
save_path: "../experiments"

# 评估脚本的路径，用于在训练后对模型进行评估
sh_path: "./evaluation"

# sclite 工具的路径，用于处理和评估语音识别结果
sclite_path: "../.bin/sclite"

# 控制矩阵乘法的精度，"medium" 表示中等精度，平衡性能和准确性
torch_float32_matmul_precision: "medium"
