# configs/callback/default.yaml
# 定义模型训练过程中的回调配置

# 监控指标，用于判断模型性能
monitor: "DEV_WER"

# 优化目标，min表示追求指标的最小值
mode: "min"

# 是否保存训练过程中的最后一个模型
save_last: true

# 保存最优模型的数量，1表示仅保存最优的模型
save_top_k: 1

# 模型保存的文件名格式，包含epoch数和监控指标的值
filename: '{epoch}-{DEV_WER:.2f}'
